"""Campo puntuacion_usuario

Revision ID: 37eaab863545
Revises: 39e87e381895
Create Date: 2026-02-25 19:35:25.928051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37eaab863545'
down_revision: Union[str, Sequence[str], None] = '39e87e381895'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patinetes', sa.Column('puntuacion_usuario', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patinetes', 'puntuacion_usuario')
    # ### end Alembic commands ###
