"""Primera Migracion

Revision ID: 39e87e381895
Revises: 
Create Date: 2026-02-25 19:18:33.673318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39e87e381895'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zonas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('codigo_postal', sa.Integer(), nullable=True),
    sa.Column('limite_velocidad', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zonas_id'), 'zonas', ['id'], unique=False)
    op.create_table('patinetes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_serie', sa.Integer(), nullable=True),
    sa.Column('modelo', sa.String(), nullable=True),
    sa.Column('bateria', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('disponible', 'en_uso', 'mantenimiento', 'sin_bateria', name='estado'), nullable=True),
    sa.Column('zona_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['zona_id'], ['zonas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patinetes_id'), 'patinetes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patinetes_id'), table_name='patinetes')
    op.drop_table('patinetes')
    op.drop_index(op.f('ix_zonas_id'), table_name='zonas')
    op.drop_table('zonas')
    # ### end Alembic commands ###
